<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">extractRates</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlleGNoYW5nZVJhdGVTdHJpbmcgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNv
ciwgImV4Y2hhbmdlUmF0ZVN0cmluZyIgKTsNClN0cmluZwl0YXJnZXRDdXJyZW5jeSA9IElEYXRh
VXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAidGFyZ2V0Q3VycmVuY3kiICk7DQpwaXBl
bGluZUN1cnNvci5kZXN0cm95KCk7DQpTdHJpbmcgcmF0ZXNTZWN0aW9uID0gZXhjaGFuZ2VSYXRl
U3RyaW5nLnNwbGl0KCJcInJhdGVzXCI6XFx7IilbMV07IA0KU3RyaW5nIHRhcmdldEN1cnJlbmN5
U2VjdGlvbiA9IHJhdGVzU2VjdGlvbi5zcGxpdCgiXCIiICsgdGFyZ2V0Q3VycmVuY3kgKyAiXCI6
IilbMV07IA0KU3RyaW5nIHJhdGUgPSB0YXJnZXRDdXJyZW5jeVNlY3Rpb24uc3BsaXQoIlssfV0i
KVswXS50cmltKCk7DQovLyBwaXBlbGluZQ0KSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3JfMSA9
IHBpcGVsaW5lLmdldEN1cnNvcigpOw0KSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwg
InJhdGUiLCByYXRlICk7DQpwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTs=</value>
</Values>
